### ISSUE TITLE
Could we include minio container into docker-compose as default fileservice for local development? 

### ISSUE THREAD

**Issue by karillio** [NFDI4Chem/nmrxiv#708]
**Describe the problem**
It is not a bug but just missed block. 
On local machine one can not use uploading part, because one needs to have AWS set-up first. 
There is meilisearch, databease but no filestorage. It is impossible to use upload withoud some external filestorage service. 

It could be like this: 
```
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_PORT:-9001}:9001'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
            MINIO_STORAGE_USE_HTTPS: 'false'
        volumes:
            - 'sailminio:/data'
        networks:
            - sail
        command: ["server", "--console-address", ":9001","/data"]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
```
`+ .env`
```
MINIO_PORT=9000
FORWARD_MINIO_PORT=9001
MINIO_ROOT_USER="${AWS_ACCESS_KEY_ID}"
MINIO_ROOT_PASSWORD="${AWS_SECRET_ACCESS_KEY}"
```

**Expected behavior**
Just a suggestion to have minio serve within docker-compose setup. 

**Additional context**
Using `development` branch.
